### ISSUE TITLE
[Question/Build] build directory is incompatible with latest version meson.

### ISSUE THREAD

**Issue by niklasjang** [nnsuite/nnstreamer#1770] opened 2019-10-15 07:06 UTC
- VMware Workstation 15 Player
  - GUEST OS : Ubuntu18.04
  - HOST OS : WINDOW 10
  
---

After `sudo apt-get update && sudo apt-get upgrade -y`, I get these errors.

```
$ cd /nnstreamer/build
$ ninja install
[1/2] Installing files.
ERROR: No module named 'mesonbuild.scripts.meson_install'
FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson --internal install /home/niklasjang/nnstreamer/build/meson-private/install.dat
ninja: build stopped: subcommand failed.
```
```
$ cd nnstreamer/build
$ meson configure
ERROR: Build directory has been generated with Meson version 0.45.1, which is incompatible with current version 0.50.1.
```

So I did,

```
$ cd nnstreamer
$ rm -r if ./build
$ meson build
$ ninja -C build install
```
And `ninja -C build insitall` works well.

I wonder if it's my mistake or bug.

**Comment by myungjoo** [comment] 2019-10-15 07:23
Whenever there is major changes in the code (usually build scripts and dependencies) or in the operating systems, you are required to do clean build.

In this case, you've updated meson; thus its configuration files are not compatible.

This is not a bug. You are just required to clean that up after upgrading meson.

**Comment by myungjoo** [comment] 2019-10-15 07:24
Because this has nothing to do with nnstreamer, but is related with the usage of meson and the given OS, I'm closing this.

**Closed by myungjoo** 2019-10-15 07:24 UTC

**Comment by niklasjang** [comment] 2019-10-15 07:42
> Because this has nothing to do with nnstreamer, but is related with the usage of meson and the given OS, I'm closing this.

I do understand. Thank you very much.
