### ISSUE TITLE
Add ppa for ubuntu disco dingo

### ISSUE THREAD

**Issue by boxerab** [nnsuite/nnstreamer#1590] opened 2019-08-12 21:23 UTC
Currently we have support for bionic beaver, but not disco. 
Thanks!

**Comment by myungjoo** [comment] 2019-08-13 02:03
I've triggered launchpad build for disco and eoan. Let's see what happens.

**Comment by myungjoo** [comment] 2019-08-13 02:10
uhoh.. I now remember why we've chose to support only LTS; The PPA repository size is 2.0GiB and tensorflow is way too big. We will wait for tensorflow downsizing (we are repackaging it to support C-API only, which reduces the binary size of TF significantly) for disco/eoan.

**Comment by myungjoo** [comment] 2019-08-13 10:13
https://answers.launchpad.net/launchpad/+question/682844

**Comment by boxerab** [comment] 2019-08-13 11:36
Thank you.

**Comment by myungjoo** [comment] 2019-08-14 06:04
Looks like EOAN's GCC has bugs, incurring tensorflow build errors (ICE). Although this is a simple regression bug that requires applying gcc patch, I won't fix it.

```
ERROR: /<<PKGBUILDDIR>>/tensorflow/core/kernels/BUILD:3114:1: C++ compilation of rule '//tensorflow/core/kernels:batch_matmul_op' failed (Exit 1)
during GIMPLE pass: alias
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:157,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/kernels/batch_matmul_op_impl.h:24,
                 from tensorflow/core/kernels/batch_matmul_op_complex.cc:16:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h: In static member function 'static void Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable, Tileable>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorChippingOp<0, Eigen::TensorMap<Eigen::Tensor<std::complex<double>, 3, 1, long int>, 16, Eigen::MakePointer> >, const Eigen::TensorContractionOp<const Eigen::array<Eigen::IndexPair<long int>, 1>, const Eigen::TensorChippingOp<0, const Eigen::TensorMap<Eigen::Tensor<const std::complex<double>, 3, 1, long int>, 16, Eigen::MakePointer> >, const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_conjugate_op<const std::complex<double> >, const Eigen::TensorChippingOp<0, const Eigen::TensorMap<Eigen::Tensor<const std::complex<double>, 3, 1, long int>, 16, Eigen::MakePointer> > >, const Eigen::NoOpOutputKernel> >; bool Vectorizable = false; bool Tileable = false]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:226:35: internal compiler error: in get_constraint_for_component_ref, at tree-ssa-structalias.c:3259
  226 |   static EIGEN_STRONG_INLINE void run(const Expression& expr,
      |                                   ^~~
Please submit a full bug report,
```

So, I'll drop EOAN for now.


If anyone's interested, please report Ubuntu of the GCC bug. It looks like gcc-9 regression anyway.

**Comment by myungjoo** [comment] 2019-08-14 08:22
Hang on. Almost there (for both EOAN and DISCO)

**Comment by myungjoo** [comment] 2019-08-14 12:59
Ok. It's almost done: Once https://github.com/nnsuite/nnstreamer/pull/1601 gets merged and launchpad rebuilds nnstreamer, nnstreamer will be available for DISCO as well, along with tensorflow 1.13.

**Comment by myungjoo** [comment] 2019-08-14 12:59
With #1599, EOAN is expected to be supported as well

**Comment by boxerab** [comment] 2019-08-14 13:14
:+1:

**Comment by myungjoo** [comment] 2019-08-14 14:49
Disco is now avaiable: https://code.launchpad.net/~nnstreamer/+recipe/nnstreamer-daily (downloadable at https://code.launchpad.net/~nnstreamer/+archive/ubuntu/ppa/+build/17417301 ), which will be published via PPA within minutes.

Anyway, EOAN requires yet another commit: #1603

**Comment by myungjoo** [comment] 2019-08-15 03:50
Done. Both Disco and Eoan are available in PPA.

**Closed by myungjoo** 2019-08-15 03:50 UTC

**Comment by boxerab** [comment] 2019-08-15 11:45
Thanks!
